apiVersion: v1
kind: Service
metadata:
  labels:
    app: jp03
  name: jp03svc
  namespace: labnote
spec:
  ports:
  - nodePort: 30683
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jp03
  type: NodePort



