apiVersion: v1
kind: Service
metadata:
  name: noteapp1svc
  namespace: labnote
  labels:
    app: noteapp1
spec:
  type: NodePort
  selector:
    app: noteapp1
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30116
