apiVersion: v1
kind: Service
metadata:
  name: noteapp1svc
  namespace: labnote
  labels:
    app: noteapp1
spec:
  type: NodePort
  selector:
    app: noteapp1
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30116

apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    app: nginx_test
spec:
  ports:
  - port: 80
    name: nginx-web
  # clusterIP Set to None
  clusterIP: None
  selector:
    app: nginx_test
