apiVersion: v1
kind: Service
metadata:
  name: service_name
  namespace: labnote
  labels:
    app: app_name
spec:
  type: NodePort
  selector:
    app: app_name
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30221



